### ISSUE TITLE
trying unsusuccessfully to install dependencies of TIMC Vectorizer notebook

### ISSUE THREAD

**Issue by youcef-hammada** [TutteInstitute/vectorizers#109]
I am in ITARP3A, I am trying to use the TIMC Vectorizer Notebook.  As per the corresponding notebook README file I linked to https://github.com/TutteInstitute/vectorizers.  I followed the steps to install the following dependencies:

<<<<<<
pip install vectorizers

wget https://github.com/TutteInstitute/vectorizers/archive/master.zip
unzip master.zip
rm master.zip
cd vectorizers-master
python setup.py install

"
After executing the above series of installs, I got the following feedback:
"
yhammad@ar2a-tarp:~/Notebooks/TIMC_Vectorizer/vectorizers-master$ python setup.py install
/disk/anaconda3/lib/python3.9/site-packages/setuptools/dist.py:739: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
  warnings.warn(
running install
/disk/anaconda3/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/disk/anaconda3/lib/python3.9/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/disk/anaconda3/lib/python3.9/site-packages/test-easy-install-457261.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /disk/anaconda3/lib/python3.9/site-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://setuptools.pypa.io/en/latest/deprecated/easy_install.html

Please make the appropriate changes for your system and try again.
>>>>>>>>

Could you please help?

Thanks

**Comment by jc-healy** [comment]
Benoit dealt with this in another channel.
