### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by cakiki** [TutteInstitute/vectorizers#96]
> We would greatly appreciate the contribution of tutorial notebooks applying vectorizer tools to diverse or interesting datasets

Hi! I was wondering what sort of contributions/tutorials you were looking for, or whether you had more concrete contribution wishes.

**Comment by cakiki** [comment]
Context: we're planning to experiment with `vectorizers` to explore the [BigScience corpus](https://bigscience.huggingface.co/blog/building-a-tb-scale-multilingual-dataset-for-language-modeling) and that could lead to interesting examples.

**Comment by lmcinnes** [comment]
I think that would be perfect if you end up with good notebooks you would be willing to share. We are well behind on getting the documentation properly organized (and written!) but the goal was to have a "tutorials" section that included walkthroughs on specifically using the tools and the hyperparameters, but also a "use cases" section which is a little more along the lines notebooks that tell interesting stories making use of vectorizers tools to help do so. This would fit well in that latter case.

Please do ping us if and when you have a notebook (or more) that you would like to share.
